name: React CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test React App
    runs-on: ubuntu-latest

    steps:
      # STEP 1: Code uthao
      - name: Checkout Code
        uses: actions/checkout@v4

      # STEP 2: Node install karo
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # STEP 3: Dependencies install
      - name: Install Dependencies
        run: npm install

      # STEP 4: Tests run
      - name: Run Tests
        run: npm test -- --watchAll=false

      # STEP 5: Docker image build
      - name: Build Docker Image
        run: docker build -t react-portfolio .
